// <auto-generated />
using System;
using EnglishVkBot.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace EnglishVkBot.DataAccess.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20191216152107_updateGuidOnLong")]
    partial class updateGuidOnLong
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("EnglishVkBot.DataAccess.Entities.LanguageDirection", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Direction");

                    b.Property<bool>("IsActive");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("LanguageDirections");
                });

            modelBuilder.Entity("EnglishVkBot.DataAccess.Entities.TranslateText", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsActive");

                    b.HasKey("Id");

                    b.ToTable("TranslatedTexts");
                });
#pragma warning restore 612, 618
        }
    }
}
